
# docker-keycloak configuration,
# add this to your docker-compose up if you want to have SSO Functions
# docker-compose -f docker-xcompose.yml -f docker-compose-keykloak.yml up
version: "3"
services:
  keycloak:
    image: jboss/keycloak
    container_name: jboss-keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=DEBUG
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_USER=keycloak
      - DB_DATABASE=keycloak
      - DB_PASSWORD=keycloak
    # Override command to enable docker protokoll  
    command: ["-b", "0.0.0.0","-Dkeycloak.profile.feature.docker=enabled"]  
    extra_hosts:
      - ${DC_HOSTNAME}:${DC_HOSTIP}
    networks:
      - devstacknetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

